title: Eduardo Moraes # your name (or website title) here
logo: "/images/logo2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Full Stack Data Scientists qualified to be Data Scientist, Data Analyst, Data Engineer or Machine Learning Engineer. 
  <br><br>
  -Develop and deploy complete ML/Deep Learning systems.<br><br>
  -Design and present A.I. solutions effectively.<br><br>
  -Implement A.I. systems on time and budget using best practices. 
  <br><br>
   <a href="https://www.linkedin.com/in/eduardomoraes/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-01Z0DYR22S # your Google Analytics tracking ID here
